export const META_ICONS = [
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/16.png',
    sizes: '16x16',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/20.png',
    sizes: '20x20',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/29.png',
    sizes: '29x29',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/32.png',
    sizes: '32x32',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/40.png',
    sizes: '40x40',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/48.png',
    sizes: '48x48',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/50.png',
    sizes: '50x50',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/55.png',
    sizes: '55x55',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/57.png',
    sizes: '57x57',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/58.png',
    sizes: '58x58',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/60.png',
    sizes: '60x60',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/64.png',
    sizes: '64x64',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/66.png',
    sizes: '66x66',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/72.png',
    sizes: '72x72',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/76.png',
    sizes: '76x76',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/80.png',
    sizes: '80x80',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/87.png',
    sizes: '87x87',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/88.png',
    sizes: '88x88',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/92.png',
    sizes: '92x92',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/100.png',
    sizes: '100x100',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/102.png',
    sizes: '102x102',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/114.png',
    sizes: '114x114',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/120.png',
    sizes: '120x120',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/128.png',
    sizes: '128x128',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/144.png',
    sizes: '144x144',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/152.png',
    sizes: '152x152',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/167.png',
    sizes: '167x167',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/172.png',
    sizes: '172x172',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/180.png',
    sizes: '180x180',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/196.png',
    sizes: '196x196',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/216.png',
    sizes: '216x216',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/256.png',
    sizes: '256x256',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/512.png',
    sizes: '512x512',
  },
  {
    rel: 'apple-touch-icon',
    type: 'image/png',
    url: '/images/Assets.xcassets.AppIcon.appiconset/1024.png',
    sizes: '1024x1024',
  },
];
