import Providers from '@/components/common/providers/Providers';
import ToastProvider from '@/components/common/toastProvider/ToastProvider';
import Header from '@/components/header/Header';
import SideBar from '@/components/sideBar/SideBar';

import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <SideBar />
          <Header />
          <main className="w-screen h-screen">{children}</main>
          <ToastProvider />
          <div id="datepiker-portal" />
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
