import localFont from 'next/font/local';

import Header from '@/components/header/Header';

import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendardFont = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
});

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={`${pretendardFont.className}`}>
        <Header />
        <main className="flex-box">{children}</main>
      </body>
    </html>
  );
}

export default RootLayout;
